---
title: "Hello \U0001F30D\U0001F30E\U0001F30F"
hero_image: images/banner.png
description: Write an interactive Python project that uses emoji
version: 4
listed: true
copyedit: true
last_tested: "2021-10-06"
steps:
  - title: You will make
  - title: Say hello
  - title: Sums and dates
    completion:
      - engaged
  - title: Roll a dice
  - title: Sentence starter
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade your project
  - title: What next?
